services:
  db:
    image: postgres:16-alpine
    container_name: web3ins-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: web3_insurance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
    driver: local